import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/tire.dart';
import '../providers/inventory_provider.dart';
import 'package:uuid/uuid.dart';

class AddSampleTires {
  static void addSampleTires(BuildContext context) {
    final sampleTires = [
      // Performance Tires
      Tire(
        id: const Uuid().v4(),
        brand: 'Michelin',
        model: 'Pilot Sport 4S',
        width: '245',
        ratio: '40',
        diameter: '18',
        price: 225.99,
        description: 'High-performance summer tire with excellent grip and handling',
        category: 'Performance',
        quantity: 8,
        storage_location1: 'Rack A',
        storage_location2: '1',
        storage_location3: 'Front',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Continental',
        model: 'ExtremeContact DWS06 Plus',
        width: '255',
        ratio: '35',
        diameter: '19',
        price: 245.99,
        description: 'Ultra-high performance all-season tire',
        category: 'Performance',
        quantity: 6,
        storage_location1: 'Rack A',
        storage_location2: '1',
        storage_location3: 'Back',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Pirelli',
        model: 'P Zero',
        width: '265',
        ratio: '35',
        diameter: '20',
        price: 285.99,
        description: 'Premium performance tire for sports cars',
        category: 'Performance',
        quantity: 4,
        storage_location1: 'Rack A',
        storage_location2: '2',
        storage_location3: 'Front',
      ),

      // All Season Tires
      Tire(
        id: const Uuid().v4(),
        brand: 'Goodyear',
        model: 'Assurance WeatherReady',
        width: '215',
        ratio: '55',
        diameter: '17',
        price: 165.50,
        description: 'All-season tire with superior wet weather performance',
        category: 'All Season',
        quantity: 12,
        storage_location1: 'Rack B',
        storage_location2: '1',
        storage_location3: 'Front',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Pirelli',
        model: 'Scorpion Verde All Season Plus II',
        width: '235',
        ratio: '60',
        diameter: '18',
        price: 195.50,
        description: 'SUV/Crossover all-season tire with low rolling resistance',
        category: 'All Season',
        quantity: 10,
        storage_location1: 'Rack B',
        storage_location2: '1',
        storage_location3: 'Back',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Firestone',
        model: 'WeatherGrip',
        width: '225',
        ratio: '65',
        diameter: '17',
        price: 155.99,
        description: 'All-weather tire with snow certification',
        category: 'All Season',
        quantity: 8,
        storage_location1: 'Rack B',
        storage_location2: '2',
        storage_location3: 'Front',
      ),

      // Winter Tires
      Tire(
        id: const Uuid().v4(),
        brand: 'Bridgestone',
        model: 'Blizzak WS90',
        width: '225',
        ratio: '65',
        diameter: '17',
        price: 185.75,
        description: 'Winter tire with exceptional snow and ice performance',
        category: 'Winter',
        quantity: 16,
        storage_location1: 'Rack C',
        storage_location2: '1',
        storage_location3: 'Front',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Nokian',
        model: 'Hakkapeliitta R5',
        width: '205',
        ratio: '55',
        diameter: '16',
        price: 195.99,
        description: 'Premium Nordic winter tire',
        category: 'Winter',
        quantity: 8,
        storage_location1: 'Rack C',
        storage_location2: '1',
        storage_location3: 'Back',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Continental',
        model: 'VikingContact 7',
        width: '215',
        ratio: '60',
        diameter: '16',
        price: 175.99,
        description: 'Winter tire for harsh conditions',
        category: 'Winter',
        quantity: 12,
        storage_location1: 'Rack C',
        storage_location2: '2',
        storage_location3: 'Front',
      ),

      // All Terrain Tires
      Tire(
        id: const Uuid().v4(),
        brand: 'BFGoodrich',
        model: 'All-Terrain T/A KO2',
        width: '275',
        ratio: '70',
        diameter: '18',
        price: 235.99,
        description: 'Rugged all-terrain tire for trucks and SUVs',
        category: 'All Terrain',
        quantity: 6,
        storage_location1: 'Rack D',
        storage_location2: '1',
        storage_location3: 'Front',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Yokohama',
        model: 'GEOLANDAR A/T G015',
        width: '265',
        ratio: '70',
        diameter: '17',
        price: 175.99,
        description: 'All-terrain tire for light trucks and SUVs',
        category: 'All Terrain',
        quantity: 8,
        storage_location1: 'Rack D',
        storage_location2: '1',
        storage_location3: 'Back',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Cooper',
        model: 'Discoverer AT3 4S',
        width: '245',
        ratio: '75',
        diameter: '16',
        price: 165.99,
        description: 'All-terrain tire with all-weather capability',
        category: 'All Terrain',
        quantity: 10,
        storage_location1: 'Rack D',
        storage_location2: '2',
        storage_location3: 'Front',
      ),

      // Mud Terrain Tires
      Tire(
        id: const Uuid().v4(),
        brand: 'Toyo',
        model: 'Open Country M/T',
        width: '285',
        ratio: '75',
        diameter: '16',
        price: 289.99,
        description: 'Mud-terrain tire for extreme off-road performance',
        category: 'Mud Terrain',
        quantity: 4,
        storage_location1: 'Rack E',
        storage_location2: '1',
        storage_location3: 'Front',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Mickey Thompson',
        model: 'Baja MTZ P3',
        width: '315',
        ratio: '70',
        diameter: '17',
        price: 325.99,
        description: 'Aggressive mud terrain tire for serious off-roading',
        category: 'Mud Terrain',
        quantity: 6,
        storage_location1: 'Rack E',
        storage_location2: '1',
        storage_location3: 'Back',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Nitto',
        model: 'Trail Grappler M/T',
        width: '295',
        ratio: '70',
        diameter: '18',
        price: 309.99,
        description: 'Hybrid mud terrain tire with reduced noise',
        category: 'Mud Terrain',
        quantity: 4,
        storage_location1: 'Rack E',
        storage_location2: '2',
        storage_location3: 'Front',
      ),

      // Economy Tires
      Tire(
        id: const Uuid().v4(),
        brand: 'Hankook',
        model: 'Kinergy PT',
        width: '195',
        ratio: '65',
        diameter: '15',
        price: 89.99,
        description: 'Economical all-season tire',
        category: 'Economy',
        quantity: 20,
        storage_location1: 'Rack F',
        storage_location2: '1',
        storage_location3: 'Front',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Kumho',
        model: 'Solus TA11',
        width: '185',
        ratio: '65',
        diameter: '15',
        price: 79.99,
        description: 'Budget-friendly all-season tire',
        category: 'Economy',
        quantity: 16,
        storage_location1: 'Rack F',
        storage_location2: '1',
        storage_location3: 'Back',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Nexen',
        model: 'N\'Priz AH5',
        width: '205',
        ratio: '60',
        diameter: '16',
        price: 95.99,
        description: 'Value-oriented all-season tire',
        category: 'Economy',
        quantity: 12,
        storage_location1: 'Rack F',
        storage_location2: '2',
        storage_location3: 'Front',
      ),

      // Run Flat Tires
      Tire(
        id: const Uuid().v4(),
        brand: 'Bridgestone',
        model: 'DriveGuard',
        width: '225',
        ratio: '45',
        diameter: '18',
        price: 215.99,
        description: 'All-season run-flat tire',
        category: 'Run Flat',
        quantity: 8,
        storage_location1: 'Rack G',
        storage_location2: '1',
        storage_location3: 'Front',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Michelin',
        model: 'Primacy ZP',
        width: '245',
        ratio: '45',
        diameter: '19',
        price: 245.99,
        description: 'Premium run-flat tire for luxury vehicles',
        category: 'Run Flat',
        quantity: 6,
        storage_location1: 'Rack G',
        storage_location2: '1',
        storage_location3: 'Back',
      ),
      Tire(
        id: const Uuid().v4(),
        brand: 'Continental',
        model: 'SSR RunFlat',
        width: '235',
        ratio: '40',
        diameter: '19',
        price: 235.99,
        description: 'Performance run-flat tire',
        category: 'Run Flat',
        quantity: 4,
        storage_location1: 'Rack G',
        storage_location2: '2',
        storage_location3: 'Front',
      ),
    ];

    final inventoryProvider = Provider.of<InventoryProvider>(context, listen: false);
    inventoryProvider.addTires(sampleTires);
  }
}
